# yaml configuration file for linker/loader of Co-RTOS

Cores: 1
ThreadsPerCore: 1

ProgramThreads:
  - CortosInitCalls:
      - main
    StackSizeInBytes: 8192

TotalMemoryInKB: 2048

# Required: for memory management support.
AddBget: True

LogLevel: DEBUG

