#include<stdio.h>
#include <stdint.h>
#include "core_portme.h"
#include "ajit_access_routines.h"
#include <math.h>

#define TESTLENGTH 256
#define NSWEEPS    16

// mapped to VA_DATA_SECTION_START  + 0x10000 for low mem
// mapped to VA_DATA_SECTION_START at 0x40040000 and above for high mem
uint32_t *cacheable_mem    = VA_DATA_SECTION_START+0x4000; 

int main()
{
	__ajit_write_serial_control_register__ ( TX_ENABLE | RX_ENABLE);

#ifndef VA_DATA_SECTION_START
	ee_printf("Error: virtual address of data section not specified\n");		
	return(1);
#endif

#ifndef CLK_FREQUENCY
	ee_printf("Error: virtual clock frequency not specified\n");		
	return(1);
#endif
	int i, err;
	uint32_t t0, t1;
	
	
	t0 = ajit_barebones_clock();
	__asm__ __volatile__("clr %l2 \n\t");
	__asm__ __volatile__("label0: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label0 \n\t " );
	__asm__ __volatile__("label1: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label1 \n\t " );
	__asm__ __volatile__("label2: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label2 \n\t " );
	__asm__ __volatile__("label3: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label3 \n\t " );
	__asm__ __volatile__("label4: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label4 \n\t " );
	__asm__ __volatile__("label5: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label5 \n\t " );
	__asm__ __volatile__("label6: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label6 \n\t " );
	__asm__ __volatile__("label7: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label7 \n\t " );
	__asm__ __volatile__("label8: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label8 \n\t " );
	__asm__ __volatile__("label9: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label9 \n\t " );
	__asm__ __volatile__("label10: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label10 \n\t " );
	__asm__ __volatile__("label11: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label11 \n\t " );
	__asm__ __volatile__("label12: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label12 \n\t " );
	__asm__ __volatile__("label13: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label13 \n\t " );
	__asm__ __volatile__("label14: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label14 \n\t " );
	__asm__ __volatile__("label15: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label15 \n\t " );
	__asm__ __volatile__("label16: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label16 \n\t " );
	__asm__ __volatile__("label17: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label17 \n\t " );
	__asm__ __volatile__("label18: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label18 \n\t " );
	__asm__ __volatile__("label19: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label19 \n\t " );
	__asm__ __volatile__("label20: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label20 \n\t " );
	__asm__ __volatile__("label21: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label21 \n\t " );
	__asm__ __volatile__("label22: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label22 \n\t " );
	__asm__ __volatile__("label23: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label23 \n\t " );
	__asm__ __volatile__("label24: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label24 \n\t " );
	__asm__ __volatile__("label25: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label25 \n\t " );
	__asm__ __volatile__("label26: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label26 \n\t " );
	__asm__ __volatile__("label27: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label27 \n\t " );
	__asm__ __volatile__("label28: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label28 \n\t " );
	__asm__ __volatile__("label29: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label29 \n\t " );
	__asm__ __volatile__("label30: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label30 \n\t " );
	__asm__ __volatile__("label31: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label31 \n\t " );
	__asm__ __volatile__("label32: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label32 \n\t " );
	__asm__ __volatile__("label33: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label33 \n\t " );
	__asm__ __volatile__("label34: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label34 \n\t " );
	__asm__ __volatile__("label35: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label35 \n\t " );
	__asm__ __volatile__("label36: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label36 \n\t " );
	__asm__ __volatile__("label37: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label37 \n\t " );
	__asm__ __volatile__("label38: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label38 \n\t " );
	__asm__ __volatile__("label39: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label39 \n\t " );
	__asm__ __volatile__("label40: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label40 \n\t " );
	__asm__ __volatile__("label41: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label41 \n\t " );
	__asm__ __volatile__("label42: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label42 \n\t " );
	__asm__ __volatile__("label43: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label43 \n\t " );
	__asm__ __volatile__("label44: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label44 \n\t " );
	__asm__ __volatile__("label45: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label45 \n\t " );
	__asm__ __volatile__("label46: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label46 \n\t " );
	__asm__ __volatile__("label47: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label47 \n\t " );
	__asm__ __volatile__("label48: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label48 \n\t " );
	__asm__ __volatile__("label49: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label49 \n\t " );
	__asm__ __volatile__("label50: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label50 \n\t " );
	__asm__ __volatile__("label51: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label51 \n\t " );
	__asm__ __volatile__("label52: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label52 \n\t " );
	__asm__ __volatile__("label53: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label53 \n\t " );
	__asm__ __volatile__("label54: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label54 \n\t " );
	__asm__ __volatile__("label55: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label55 \n\t " );
	__asm__ __volatile__("label56: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label56 \n\t " );
	__asm__ __volatile__("label57: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label57 \n\t " );
	__asm__ __volatile__("label58: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label58 \n\t " );
	__asm__ __volatile__("label59: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label59 \n\t " );
	__asm__ __volatile__("label60: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label60 \n\t " );
	__asm__ __volatile__("label61: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label61 \n\t " );
	__asm__ __volatile__("label62: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label62 \n\t " );
	__asm__ __volatile__("label63: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label63 \n\t " );
	__asm__ __volatile__("label64: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label64 \n\t " );
	__asm__ __volatile__("label65: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label65 \n\t " );
	__asm__ __volatile__("label66: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label66 \n\t " );
	__asm__ __volatile__("label67: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label67 \n\t " );
	__asm__ __volatile__("label68: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label68 \n\t " );
	__asm__ __volatile__("label69: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label69 \n\t " );
	__asm__ __volatile__("label70: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label70 \n\t " );
	__asm__ __volatile__("label71: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label71 \n\t " );
	__asm__ __volatile__("label72: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label72 \n\t " );
	__asm__ __volatile__("label73: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label73 \n\t " );
	__asm__ __volatile__("label74: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label74 \n\t " );
	__asm__ __volatile__("label75: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label75 \n\t " );
	__asm__ __volatile__("label76: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label76 \n\t " );
	__asm__ __volatile__("label77: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label77 \n\t " );
	__asm__ __volatile__("label78: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label78 \n\t " );
	__asm__ __volatile__("label79: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label79 \n\t " );
	__asm__ __volatile__("label80: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label80 \n\t " );
	__asm__ __volatile__("label81: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label81 \n\t " );
	__asm__ __volatile__("label82: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label82 \n\t " );
	__asm__ __volatile__("label83: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label83 \n\t " );
	__asm__ __volatile__("label84: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label84 \n\t " );
	__asm__ __volatile__("label85: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label85 \n\t " );
	__asm__ __volatile__("label86: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label86 \n\t " );
	__asm__ __volatile__("label87: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label87 \n\t " );
	__asm__ __volatile__("label88: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label88 \n\t " );
	__asm__ __volatile__("label89: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label89 \n\t " );
	__asm__ __volatile__("label90: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label90 \n\t " );
	__asm__ __volatile__("label91: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label91 \n\t " );
	__asm__ __volatile__("label92: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label92 \n\t " );
	__asm__ __volatile__("label93: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label93 \n\t " );
	__asm__ __volatile__("label94: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label94 \n\t " );
	__asm__ __volatile__("label95: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label95 \n\t " );
	__asm__ __volatile__("label96: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label96 \n\t " );
	__asm__ __volatile__("label97: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label97 \n\t " );
	__asm__ __volatile__("label98: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label98 \n\t " );
	__asm__ __volatile__("label99: \n\t " );
	__asm__ __volatile__( " clr %l1 \n\t" );
	__asm__ __volatile__( " add %l1, 1, %l1  \n\t " );
	__asm__ __volatile__( " cmp %l2, %l1  \n\t " );
	__asm__ __volatile__( " bg label99 \n\t " );


	t1 = ajit_barebones_clock();
	
	
	ee_printf("Time taken by instrs in ticks = %u\n",(t1-t0));

	ee_printf("done\n");
}

